### ISSUE TITLE
API - Accounts | saldos-da-conta | availableAmount

### ISSUE THREAD

**Issue by olegkvyatkovskiy** [Sensedia/massadedados#9]
https://openbanking-brasil.github.io/areadesenvolvedor/#saldos-da-conta
https://openbanking-brasil.github.io/areadesenvolvedor/swagger/swagger_accounts_apis.yaml
```
        availableAmount:
          type: number
          format: double
          pattern: '(-?\d{15}(.\d{4}?))$'
          description: 'Saldo disponível para utilização imediata. No caso de conta de depósito a vista, sem considerar cheque especial e investimentos atrelados a conta. Admite saldo negativo. Expresso em valor monetário com 4 casas decimais.'
          maxLength: 19
          minLength: 0
          nullable: true
          example: 100000.04
```

**pattern** does not correspond to **double** format and to **example** specified
